routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController@index')->name('index');

Route::resource('property', 'PropertyController');
Route::get('property/{subdivision}/subdivision', 'PropertyController@subdivision')->name('property.subdivision');

Route::resource('brokers', 'BrokersController');
Route::post('brokers/{broker_id}/rate', 'BrokersController@rate')->name('brokers.rate');

Route::prefix('register')->name('register.')->group(function(){
	Route::get('/', 'RegistrationController@index')->name('index');
	Route::post('store', 'RegistrationController@store')->name('store');
});

Route::prefix('login')->name('login.')->group(function(){
	Route::get('/', 'AuthenticationController@index')->name('index');
	Route::post('authenticate', 'AuthenticationController@authentication')->name('authenticate');
	Route::get('logout', 'AuthenticationController@logout')->middleware('authenticated.user')->name('logout');
});

Route::middleware('authenticated.user')->group(function(){
	Route::middleware('admin.user')->prefix('admin')->name('admin.')->group(function(){
		Route::resource('users', 'UsersController');
		Route::get('activity', 'UserActivityController@index')->name('activity.index');
	});

	Route::prefix('profile')->name('profile.')->group(function(){
		Route::get('/', 'ProfileController@index')->name('index');
		Route::post('store', 'ProfileController@store')->name('store');
	});

	Route::resource('cart', 'CartController');

	Route::middleware('is_broker')->group(function(){
		Route::resource('listing', 'ListingController');
		Route::get('listing/actions/{id}', 'ListingController@actions')->name('listing.actions');
		Route::post('listing/actions-submit/{id}', 'ListingController@actions_submit')->name('listing.actions_submit');

		Route::get('listing/{id}/image', 'ListingController@image')->name('listing.image');
		Route::post('listing/{id}/image', 'ListingController@image_upload')->name('listing.image_upload');
		Route::get('listing/{listing_id}/image/{id}/remove', 'ListingController@remove')->name('image.remove');
		Route::get('listing/{listing_id}/image/{id}/default/{status}', 'ListingController@default')->name('image.default');
	});
	Route::get('unit-address-search', 'ListingController@search')->name('listing.unit-address-search');
	Route::get('unit-address-select', 'ListingController@select')->name('listing.unit-address-select');

	Route::get('listing-viewed', 'ViewedController@index')->name('listing.viewed');


	Route::resource('inbox', 'InboxController');
	Route::get('user/search', 'InboxController@search')->name('inbox.search');
	Route::get('notification', 'ViewedController@notification')->name('viewed.notification');

	Route::prefix('reports')->name('reports.')->group(function(){
		Route::get('listing', 'ReportsListingController@index')->name('listing');
		Route::get('listing-print', 'ReportsListingController@print')->name('listing-print');
	});

});

resources/views/brokers.blade.php
@extends('layout.master')

@section('page-title', 'Broker`s')

@section('content')
<style type="text/css">
    .fa-star-color {
        color: #f7c42d!important;
    }
    .thumbnail {
        width: 250px!important;
    }
</style>

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
		<h3>Our Broker`s</h3>

		<div class="grid-x">
            @foreach($rows as $row)
            <div class="cell large-4">
                <img class="thumbnail" src="{{ (is_null($row->image)) ? 'https://placehold.it/250x400' : $row->image }}">
                <p class="lead">
                	<a href="{{ route('brokers.show', $row->id) }}">{{ $row->first_name . ' ' . $row->last_name }}</a>
                </p>
                <p class="subheader">
                	Agency Name : {{ $row->agency_name }}<br>
                	Member Since : {{ $row->created_at->format('F d, Y') }}<br>
                	Ratings : {!! $row->rating !!}
                </p>
                <br>
            </div>
			@endforeach
		</div>

        {!! $rows->appends(['search'=>''])->links('vendor.pagination.default') !!}
    </div>

</div>

@endsection

resources/views/index.blade.php
@extends('layout.master-full')

@section('page-title', 'Home')

@section('content')
<style type="text/css">
    #realEstateMenu {

    }
    p.lead {
        margin-bottom: 4px!important;
    }
    .thumbnail {
        width: 250px!important;
        height: 250px!important;
    }
    html, body {
        height: 100%; 
    }
    .bg {
        background-image: url('images/plan-and-manage-hero.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: top;
        width: 100%;
        height: 100%;
        padding-top: 20%;
    }
    @media screen and (max-width: 39.9375em) {
        #find-a-property {
            padding-top: 400px;
        }
        .bg-banner {
            font-size: 36px!important;
            padding-bottom: 0!important;
            padding-top: 0!important;
        }
    }
    @media screen and (min-width: 40em) and (max-width: 63.9375em) {
        #find-a-property {
            padding-top: 400px;
        }
        #featured-prop {
            margin-top: 100px;
        }
        .bg-banner {
            font-size: 36px!important;
            padding-bottom: 0!important;
            padding-top: 0!important;
        }
    }
    .bg-banner {
        position: absolute;
        font-size: 64px;
        font-weight: bold;
        font-stretch: extra-expanded;
        color: #fff;
        top: 100px;
        text-align: center;
        width: 100%;
    }
</style>
<div class="bg">
    <!-- <h1 class="bg-banner text-center">REAL ESTATE PROPERTY LOCATOR </h1> -->
    <div id="find-a-property" class="grid-x">
        <div class="cell large-2 small-12"></div>
        <div class="cell large-3 small-12">
            <div class="callout">
                <h3 class="text-center margin-top-custom-50">Find a property</h3>
                <div class="grid-x margin-top-custom-20">
                    <div class="cell large-1"></div>
                    <div class="cell auto small-12">
                        <form action="{{ route('property.index') }}" method="get">
                            <select name="type">
                                <option value="">All</option>
                                <option value="1">Lot</option>
                                <option value="2">House & Lot</option>
                            </select>
                            <input type="text" name="search" placeholder="Search Location, Lot, Bedrooms, Floor">
                            <button class="button" type="submit"><i class="fa fa-search"></i> Search</button>
                        </form>
                    </div>
                    <div class="cell large-1"></div>
                </div>
            </div>
            <div class="cell auto"></div>
        </div>
    </div>
</div>

<div id="featured-prop" class="container margin-top-custom-50">
    <h3 class="text-center">Featured Properties</h3>
    <div class="grid-x grid-padding-x">
        @foreach($properties as $property)
        <div class="cell large-3 small-12">
            <div class="callout">
                <?php $img = $property->images->where('primary', 1)->first(); ?>
                <p class="text-center">
                    @if(is_null($img))
                    <img class="thumbnail" src="https://placehold.it/250x370">
                    @else
                    <img class="thumbnail" src="{{ $img->location }}">
                    @endif
                </p>
                <p class="lead text-center"><a href="{{ route('property.show', $property->id) }}">{{ $property->subdivision }}</a></p>
                <p class="subheader text-center">
                    <i class="fa fa-map-marker"></i> {{ $property->address . ', ' . $property->city }}<br>
                </p>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection