routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController@index')->name('index');

Route::resource('property', 'PropertyController');
Route::get('property/{subdivision}/subdivision', 'PropertyController@subdivision')->name('property.subdivision');

Route::resource('brokers', 'BrokersController');
Route::post('brokers/{broker_id}/rate', 'BrokersController@rate')->name('brokers.rate');

Route::prefix('register')->name('register.')->group(function(){
	Route::get('/', 'RegistrationController@index')->name('index');
	Route::post('store', 'RegistrationController@store')->name('store');
});

Route::prefix('login')->name('login.')->group(function(){
	Route::get('/', 'AuthenticationController@index')->name('index');
	Route::post('authenticate', 'AuthenticationController@authentication')->name('authenticate');
	Route::get('logout', 'AuthenticationController@logout')->middleware('authenticated.user')->name('logout');
});

Route::middleware('authenticated.user')->group(function(){
	Route::middleware('admin.user')->prefix('admin')->name('admin.')->group(function(){
		Route::resource('users', 'UsersController');
		Route::get('activity', 'UserActivityController@index')->name('activity.index');
	});

	Route::prefix('profile')->name('profile.')->group(function(){
		Route::get('/', 'ProfileController@index')->name('index');
		Route::post('store', 'ProfileController@store')->name('store');
	});

	Route::resource('cart', 'CartController');

	Route::middleware('is_broker')->group(function(){
		Route::resource('listing', 'ListingController');
		Route::get('listing/actions/{id}', 'ListingController@actions')->name('listing.actions');
		Route::post('listing/actions-submit/{id}', 'ListingController@actions_submit')->name('listing.actions_submit');

		Route::get('listing/{id}/image', 'ListingController@image')->name('listing.image');
		Route::post('listing/{id}/image', 'ListingController@image_upload')->name('listing.image_upload');
		Route::get('listing/{listing_id}/image/{id}/remove', 'ListingController@remove')->name('image.remove');
		Route::get('listing/{listing_id}/image/{id}/default/{status}', 'ListingController@default')->name('image.default');
	});
	Route::get('unit-address-search', 'ListingController@search')->name('listing.unit-address-search');
	Route::get('unit-address-select', 'ListingController@select')->name('listing.unit-address-select');

	Route::get('listing-viewed', 'ViewedController@index')->name('listing.viewed');


	Route::resource('inbox', 'InboxController');
	Route::get('user/search', 'InboxController@search')->name('inbox.search');
	Route::get('notification', 'ViewedController@notification')->name('viewed.notification');

	Route::prefix('reports')->name('reports.')->group(function(){
		Route::get('listing', 'ReportsListingController@index')->name('listing');
		Route::get('listing-print', 'ReportsListingController@print')->name('listing-print');
	});

});

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ListingAction;
use App\ListingOwner;

class Listing extends Model
{
    protected $connection = 'mysql';
    protected $table = 'listing';
    protected $guarded = [];

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function type()
    {
        return $this->hasOne('App\ListingType', 'id', 'listing_type_id');
    }

    public function image()
    {
        return $this->hasOne('App\ImageListing', 'id', 'listing_id');
    }

    public function images()
    {
        return $this->hasMany('App\ImageListing');
    }

    public function action()
    {
        return $this->hasMany('App\ListingAction', 'id', 'listing_id');
    }

    public function listing_owners()
    {
        #return $this->belongsTo('App\ListingOwner', 'id', 'listing_id');
        return ListingOwner::whereListingId($this->id)->get();
    }

    public function views()
    {
        $count = AccessLog::whereListingId($this->id)->count();
        return $count;
        #return $this->belongsTo('App\AccessLog', 'id', 'listing_id');
    }

    public function getListStatusAttribute()
    {
        if (is_null($this->status)) {
            return 'available';
        } elseif ($this->status == 0) {
            return 'hold';
        } elseif ($this->status == 1) {
            return 'reserved';
        }
    }

    public function view()
    {
        return $this->hasOne('App\AccessLog', 'id', 'listing_id');
    }

    public function listing_rating()
    {
        return $this->hasOne('App\ListingRating', 'id', 'listing_id');
    }

    public function getClientNameAttribute()
    {
        $action = ListingAction::with('client')->whereListingId($this->id)->whereUserId($this->user_id)->orderBy('created_at', 'DESC')->first();
        if (is_null($action)) {
            return '';
        } elseif(is_null($action->client)) {
            return '';
        }
        
        return $action->client->full_name;
    }
}

app/ListingAction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListingAction extends Model
{
    protected $connection = 'mysql';
    protected $table = 'listing_actions';
    protected $guarded = [];

    public function listing()
    {
    	return $this->belongsTo('App\Listing', 'id', 'listing_type_id');
    }

    public function client()
    {
    	return $this->hasOne('App\User', 'id', 'client_id');
    }
}

app/ListingType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListingType extends Model
{
    protected $connection = 'mysql';
    protected $table = 'listing_type';
    protected $guarded = [];

    public function listing()
    {
    	return $this->belongsTo('App\Listing', 'id', 'listing_type_id');
    }
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ImageListing;
use App\Listing;
use App\ListingOwner;
use App\ListingType;
use App\ListingAction;
use Sentinel;
use Illuminate\Support\Str;
use Storage;
use \Carbon\Carbon;

class ListingController extends Controller
{
    public function index(Request $request)
    {
        $status = '';
        $type = '';
        $search = '';
        #$listing_query = Listing::whereUserId(Sentinel::getUser()->id);
        $user_id = Sentinel::getUser()->id;
        $listing_query = Listing::whereIn('id', function($query) use ($user_id){
            return $query->select('listing_id')->from('listing_owners')->where('user_id', $user_id);
        });

        if ($request->has('search')) {
            $status = $request->status;
            $type = $request->type;
            $search = $request->search;

            if ($status != '') {
                if ($status == 'null') {
                    $listing_query = $listing_query->whereNull('status');
                } else {
                    $listing_query = $listing_query->whereStatus($status);
                }
            }

            if ($type != '') {
                $listing_query = $listing_query->whereListingTypeId($type);
            }

            if ($search != '') {
                $listing_query = $listing_query->where(function($query) use ($search){
                    $query->where('subdivision', 'LIKE', "%$search%")->orWhere('address', 'LIKE', "%$search%")->orWhere('city', 'LIKE', "%$search%");
                });
            }

        }
        $listing = $listing_query->paginate(50);
        #$listing = $listing_query->toSql();dd($listing);
        $listing_types = ListingType::get();

        $data = compact('listing', 'listing_types', 'search', 'status', 'type');
        return view('listing.index', $data);
    }

    public function create(Request $request)
    {
        $route = route('listing.store');
        $title = old('title');
        $price = old('price');
        $listing_type_id = old('listing_type_id');
        $lot_area = old('lot_area');
        $floor_area = old('floor_area');
        $floor = old('floor');
        $bedrooms = old('bedrooms');
        $bathrooms = old('bathrooms');
        $subdivision = old('subdivision');
        $address = old('address');
        $city = old('city');
        $description = old('description');

        $types = ListingType::get();

        $data = compact('route', 'title', 'price', 'listing_type_id', 'lot_area', 'floor_area', 'floor', 'bedrooms', 'bathrooms', 'subdivision', 'address', 'city', 'description', 'types');

        return view('listing.form', $data);
    }

    public function store(Request $request)
    {
        $request->validate([
            'listing_type_id' => 'required',
            'title' => 'required',
            'price' => 'required|numeric',
            'lot_area' => 'required',
            'floor_area' => 'required_if:listing_type_id,2|numeric',
            'floor' => 'required_if:listing_type_id,2',
            'bedrooms' => 'required_if:listing_type_id,2',
            'bathrooms' => 'required_if:listing_type_id,2',
            'subdivision' => 'required',
            'address' => 'required',
            'city' => 'required',
            'description' => 'required'
        ],[
            'floor.required_if' => 'The floor field is required.',
            'bedrooms.required_if' => 'The bedrooms field is required.',
            'bathrooms.required_if' => 'The bathrooms field is required.'
        ]);

        $data = $request->except('_token', 'title_search_id');
        $data['user_id'] = Sentinel::getUser()->id;
        $id = $request->title_search_id;
        if ($request->title_search_id == 0) {
            $listing = Listing::create($data);
            $id = $listing->id;
        #} else {
            #ListingOwner::create(['listing_id' => $request->title_search_id, 'user_id' => Sentinel::getUser()->id]);
            #return redirect()->back()->with('success_msg', 'listing successfuly added.');
        }
        ListingOwner::create(['listing_id' => $id, 'user_id' => Sentinel::getUser()->id]);
        return redirect()->back()->with('success_msg', 'You successfuly created a new listing.');
    }

    public function edit($id, Request $request)
    {
        $row = Listing::find($id);

        if (!$row) {
            abort(404);
        }

        $route = route('listing.update', $id);

        $title = $row->title;
        $price = $row->price;
        $listing_type_id = $row->listing_type_id;
        $lot_area = $row->lot_area;
        $floor_area = $row->floor_area;
        $floor = $row->floor;
        $bedrooms = $row->bedrooms;
        $bathrooms = $row->bathrooms;
        $subdivision = $row->subdivision;
        $address = $row->address;
        $city = $row->city;
        $description = $row->description;

        $types = ListingType::get();

        $data = compact('route', 'id', 'title', 'price', 'listing_type_id', 'lot_area', 'floor_area', 'floor', 'bedrooms', 'bathrooms', 'subdivision', 'address', 'city', 'description', 'types');

        return view('listing.form', $data);
    }

    public function update($id, Request $request)
    {
        $row = Listing::find($id);

        if (!$row) {
            abort(404);
        }

        $request->validate([
            'listing_type_id' => 'required',
            'title' => 'required',
            'price' => 'required|numeric',
            'lot_area' => 'required',
            'floor_area' => 'required_if:listing_type_id,2|numeric',
            'floor' => 'required_if:listing_type_id,2',
            'bedrooms' => 'required_if:listing_type_id,2',
            'bathrooms' => 'required_if:listing_type_id,2',
            'subdivision' => 'required',
            'address' => 'required',
            'city' => 'required',
            'description' => 'required'
        ],[
            'floor.required_if' => 'The floor field is required.',
            'bedrooms.required_if' => 'The bedrooms field is required.',
            'bathrooms.required_if' => 'The bathrooms field is required.'
        ]);

        $data = $request->except('_token', '_method');

        Listing::whereId($id)->update($data);

        return redirect()->back()->with('success_msg', 'You successfuly created a new listing.');
    }

    public function show($id)
    {
        return view('listing.show');
    }

    public function image($id)
    {
        $listing = Listing::find($id);
        $rows = ImageListing::whereListingId($id)->paginate(50);

        if (!$rows) {
            abort(404);
        }

        $route = route('listing.image_upload', $id);

        $data = compact('listing', 'rows', 'route');
        return view('listing.image', $data);
    }

    public function image_upload($id, Request $request)
    {
        $request->validate([
            'vicinity_map' => 'image',
            'image' => 'image'
        ]);
        $user           = Sentinel::getUser();

        if($request->has('vicinity_map')) {
            $vicinity_map   = $request->vicinity_map;
            $vicinity_map_extension = $request->vicinity_map->getClientOriginalExtension();
            $vicinity_map_name      = date('Ymdhis') . '_' . Str::random(10) . '.' . $vicinity_map_extension;
            $vicinity_map_location  = 'images/vicinity-map/'.$id;

            if (Storage::exists($vicinity_map_location)) {
                Storage::deleteDirectory($vicinity_map_location);
            }
            Storage::makeDirectory($vicinity_map_location);

            $request->vicinity_map->move(public_path($vicinity_map_location), $vicinity_map_name);

            Listing::whereId($id)->update([
                'vicinity_map'=>$vicinity_map_location.'/'.$vicinity_map_name
            ]);
        }

        if($request->has('image')) {
            $file           = $request->image;
            $extension      = $request->image->getClientOriginalExtension();
            $file_name      = date('Ymdhis') . '_' . Str::random(10) . '.' . $extension;
            $file_location  = 'images/listing/'.$id;

            if (Storage::exists($file_location)) {
                Storage::deleteDirectory($file_location);
            }
            Storage::makeDirectory($file_location);

            $request->image->move(public_path($file_location), $file_name);

            ImageListing::create([
                'listing_id'=>$id,
                'user_id'=>$user->id,
                'location'=>$file_location.'/'.$file_name
            ]);
        }

        return redirect()->route('listing.image_upload', $id)->with('success_msg', 'Image successfully uploaded!');
    }

    public function remove($listing_id, $id)
    {
        $row = ImageListing::whereId($id)->first();

        if (!$row) {
            abort(404);
        }
        ImageListing::whereId($id)->delete();
        return redirect()->route('listing.image', $listing_id)->with('success_msg', 'Image successfully remove!');
    }

    public function default($listing_id, $id, $status)
    {
        $row = ImageListing::whereId($id)->first();

        if (!$row) {
            abort(404);
        }

        ImageListing::whereListingId($listing_id)->update(['primary'=>0]);
        if ($status <= 0) {
            $status = 0;
        } else {
            $status = 1;
        }
        ImageListing::whereId($id)->update(['primary'=>1]);
        return redirect()->route('listing.image', $listing_id)->with('success_msg', 'Primary Image successfully set!');
    }

    public function actions($id)
    {
        $route = route('listing.actions_submit', $id);
        $row = Listing::find($id);

        $status = $row->status;
        $listing_type_name = $row->type->name;
        $listing_type_id = $row->listing_type_id;
        $lot_area = $row->lot_area;
        $floor_area = $row->floor_area;
        $floor = $row->floor;
        $bedrooms = $row->bedrooms;

resources/views/listing/actions.blade.php
@extends('layout.master')

@section('page-title', 'Listing Actions')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
        <h3>Listing Actions</h3>
        @include('partials.error-messages')
        <form action="{{ $route }}" method="post">

            <div class="grid-x grid-padding-x">
                <div class="cell large-4">
                    <label>Client
                        <input type="text" id="search_client" name="search_client" value="{{ $client_name }}" placeholder="Search..." />
                        <input type="hidden" id="client_id" name="client_id" value="{{ $client_id }}" />
                    </label>
                </div>
                <div class="cell large-2">
                    <label>
                        Status
                        <select name="status" id="status">
                            <option value="">Available</option>
                            <option value="0">Hold</option>
                            <option value="1">Reserved</option>
                        </select>
                    </label>
                </div>
                <div class="cell large-6"></div>
                <div class="cell large-2">
                    <label>
                        Property Type
                        <input type="text" name="listing_type_name" id="listing_type_name" value="{{ $listing_type_name }}" readonly="">
                    </label>
                </div>
                <div class="cell large-2 lot-items">
                    <label>
                        Lot Area
                        <input type="text" name="lot_area" id="lot_area" value="{{ $lot_area }}" readonly="">
                    </label>
                </div>
                <div class="cell large-2 house-and-lot-items" style="display: none;">
                    <label>
                        Floor Area
                        <input type="text" name="floor_area" id="floor_area" value="{{ $floor_area }}" readonly="" disabled="disabled">
                    </label>
                </div>
                <div class="cell large-2 house-and-lot-items" style="display: none;">
                    <label>
                        Floor
                        <input type="number" name="floor" id="floor" value="{{ $floor }}" readonly="" disabled="disabled">
                    </label>
                </div>

                <div class="cell large-2 house-and-lot-items" style="display: none;">
                    <label>
                        Bedrooms
                        <input type="number" name="bedrooms" id="bedrooms" value="{{ $bedrooms }}" readonly="" disabled="disabled">
                    </label>
                </div>
                <div class="cell large-2 house-and-lot-items" style="display: none;">
                    <label>
                        Bathrooms
                        <input type="number" name="bathrooms" id="bathrooms" value="{{ $bathrooms }}" readonly="" disabled="disabled">
                    </label>
                </div>
            </div>

            <label>
                Subdivision
                <input type="text" name="subdivision" id="subdivision" value="{{ $subdivision }}" readonly="">
            </label>

            <label>
                Address
                <input type="text" name="address" id="address" value="{{ $address }}" readonly="">
            </label>

            <label>
                City
                <input type="text" name="city" id="city" value="{{ $city }}" readonly="">
            </label>

            <label>
                Description
                <textarea name="description" id="description" rows="5" readonly="">{{ $description }}</textarea>
            </label>
            
            <div class="grid-x">
                <div class="cell auto"></div>
                <div class="cell large-2">
                    <button class="button success expanded margin-top-custom-40" type="submit">Submit</button>
                    @csrf()
                    <a class="button expanded" href="{{ route('listing.index') }}">Back</a>
                </div>
                <div class="cell auto"></div>
            </div>
        </form>
    </div>

</div>

@endsection

@section('scripts')
<script type="text/javascript">
    $("#status").val('{{ $status }}');
    <?php
    if ($listing_type_id == 1) {
        echo '$(".house-and-lot-items").hide();';
        echo '$(".house-and-lot-items input").attr("disabled", true);';
    } elseif ($listing_type_id == 2) {
        echo '$(".house-and-lot-items").show();';
        echo '$(".house-and-lot-items input").attr("disabled", false);';
    }
    ?>
    $('#listing_type_id').val('{{ $listing_type_id }}');

    $(function(){
        $('#listing_type_id').change(function(){
            var value = $(this).val();
            if (value == 1) {
                $('.house-and-lot-items').hide();
                $(".house-and-lot-items input").attr("disabled", true);
            } else if (value == 2) {
                $('.house-and-lot-items').show();
                $(".house-and-lot-items input").attr("disabled", false);
            } else {
                $('.house-and-lot-items ').hide();
            }
        });

        var xhr_search = null;

        $("#search_client").autocomplete({
            source: function(request, response){
                xhr_search = $.ajax({
                    type : 'get',
                    url : '{{ route("inbox.search") }}',
                    cache : false,
                    dataType : "json",
                    data : "keyword=" + request.term,
                    async : false, 
                    beforeSend: function(xhr){
                        if (xhr_search != null)
                        {
                            xhr_search.abort();
                        }
                    }
                }).done(function(result_set) {
                    response($.map(result_set, function (key, value) {
                        return {
                            label: key,
                            value: value
                        };
                    }));
                }).fail(function(jqXHR, textStatus) {

                });
            },
            minLength: 2,
            select: function( event, ui ) {
                $('#client_id').val(ui.item.value);
                $('#search_client').val(ui.item.label);
                $('#status').val(1);
                return false;
            }
        });
    });
</script>
@endsection

resources/views/listing/image.blade.php
@extends('layout.master')

@section('page-title', 'Listing')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
    
        <h3>Images</h3>
        @include('partials.error-messages')

        <div class="grid-x grid-padding-x">
        	
            <div class="cell large-2">

		        <form action="{{ $route }}" method="post" enctype="multipart/form-data">
                    <label>
                        Vicinity Map
                        <input type="file" name="vicinity_map" id="vicinity_map">
                    </label>

	                <label>
	                    Image
	                    <input type="file" name="image" id="image">
	                </label>
	                @csrf()
	                <button class="button success expanded margin-top-custom-40" type="submit">Upload</button>
		        	
		        </form>
            	
            </div>

            <div class="cell auto">
                <div class="grid-x grid-padding-x">
                    @if($listing->vicinity_map != '')
                    <div class="cell large-4">
                        <img class="thumbnail" src="{{ asset($listing->vicinity_map) }}">
                    </div>
                    @endif
                	@foreach($rows as $row)
                	<div class="cell large-4">
                        <a href="javascript:void(0)"><img class="thumbnail" src="{{ asset($row->location) }}"></a>
                        <div>
                            @if($row->primary == 1)
                            <a class="button tiny" href="{{ route('image.default', ['listing_id'=>$row->listing_id, 'id'=>$row->id, 'status'=>0]) }}">Default</a>
                            @else
                            <a class="button tiny secondary" href="{{ route('image.default', ['listing_id'=>$row->listing_id, 'id'=>$row->id, 'status'=>1]) }}">Default</a>
                            @endif
                            <a class="button tiny alert" href="{{ route('image.remove', ['listing_id'=>$row->listing_id, 'id'=>$row->id]) }}">Remove</a>
                        </div>
                	</div>
                	@endforeach
                </div>
            </div>

        </div>
    </div>

</div>

@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/listing/index.blade.php
@extends('layout.master')

@section('page-title', 'Listing')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
        <h3>My Listing</h3>
        <form method="get" action="">
            <div class="grid-x">
                <div class="cell large-2">
                    <select name="status" id="status">
                        <option value="">All</option>
                        <option value="null">Available</option>
                        <option value="0">Hold</option>
                        <option value="1">Reserved</option>
                    </select>
                </div>
                <div class="cell large-2">
                    <select name="type" id="type">
                        <option value="">All</option>
                        @foreach($listing_types as $listing_type)
                        <option value="{{ $listing_type->id }}">{{ $listing_type->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="cell large-2">
                    <input type="text" name="search" value="{{ $search }}">
                </div>
                <div class="cell large-1">
                    <button class="button" type="submit">Search</button>
                </div>
                <div class="cell auto">&nbsp;</div>
            </div>
        </form>
        <table width="100%">
            <thead>
                <tr>
                    <th width="10%"></th>
                    <th width="10%" class="text-center">Status</th>
                    <th width="10%">Type</th>
                    <th width="25%">Subdivision</th>
                    <th width="30%">Address</th>
                    <th width="15%" class="text-right">Price</th>
                </tr>
            </thead>
            <tbody>
            @foreach($listing as $row)
                <tr>
                    <td>
                        <a href="{{ route('listing.edit', $row->id) }}" title="Edit"><i class="fa fa-edit"></i></a>
                        <a href="{{ route('listing.image', $row->id) }}" title="Images"><i class="fa fa-image"></i></a>
                        <a href="{{ route('listing.actions', $row->id) }}" title="Action"><i class="fa fa-cog"></i></a>
                    </td>
                    <td class="text-center">{{ ucwords($row->list_status) }}</td>
                    <td>{{ $row->type->name }}</td>
                    <td>{{ $row->subdivision }} {{ $row->title }}</td>
                    <td>{{ $row->address }} {{ $row->city }}</td>
                    <td class="text-right">{{ number_format($row->price, 2) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $listing->appends(['search'=>$search])->links('vendor.pagination.default') !!}
    </div>

</div>

@endsection

@section('scripts')
<script type="text/javascript">
    $(function(){
        $('#status').val('{{ $status }}');
        $('#type').val('{{ $type }}');
    });
</script>
@endsection

resources/views/listing/notification.blade.php
@extends('layout.master')

@section('page-title', 'Listing')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
        <h3>My Listing Notification</h3>
        <table width="100%">
            <thead>
                <tr>
                    <th width="10%" class="text-center">Status</th>
                    <th width="40%">Subdivision</th>
                    <th width="30%">Address</th>
                    <th width="20%" class="text-right">Price</th>
                </tr>
            </thead>
            <tbody>
            @foreach($rows as $row)
                <?php
                if(is_null($row->seen_at)) {
                    App\ListingOwner::whereId($row->id)->update(['seen_at'=>DB::raw('NOW()')]);
                }
                ?>
                <tr>
                    <td class="text-center">
                        @if (is_null($row->status))
                            AVAILABLE
                        @elseif ($row->status == 0)
                            HOLD
                        @elseif ($row->status == 1)
                            RESERVED
                        @endif
                    </td>
                    <td>{{ $row->subdivision }} {{ $row->title }}</td>
                    <td>{{ $row->address }} {{ $row->city }}</td>
                    <td class="text-right">{{ number_format($row->price, 2) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $rows->links('vendor.pagination.default') !!}
    </div>

</div>

@endsection

resources/views/listing/show.blade.php
@extends('layout.master')

@section('page-title', 'Listing')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
    
    </div>

</div>

@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/listing/viewed.blade.php
@extends('layout.master')

@section('page-title', 'Viewed Property')

@section('content')
<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
        <h3>Viewed Property</h3>
        <table width="100%">
            <thead>
                <tr>
                    <th width="30%">Subdivision</th>
                    <th width="30%">Address</th>
                    <th width="20%" class="text-center">Status</th>
                    <th width="20%">Seen At</th>
                </tr>
            </thead>
            <tbody>
            @foreach($rows as $row)
                <tr>
                    <td><a href="{{ route('property.show', $row->id) }}" title="Edit">{{ $row->listing->subdivision }}</a></td>
                    <td>{{ $row->listing->address }}</td>
                    <td class="text-center">{{ ucwords($row->listing->list_status) }}</td>
                    <td>{{ $row->created_at->format('M. d, Y H:i A') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $rows->appends(['search'=>''])->links('vendor.pagination.default') !!}
    </div>

</div>

@endsection