routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'IndexController@index')->name('index');

Route::resource('property', 'PropertyController');
Route::get('property/{subdivision}/subdivision', 'PropertyController@subdivision')->name('property.subdivision');

Route::resource('brokers', 'BrokersController');
Route::post('brokers/{broker_id}/rate', 'BrokersController@rate')->name('brokers.rate');

Route::prefix('register')->name('register.')->group(function(){
	Route::get('/', 'RegistrationController@index')->name('index');
	Route::post('store', 'RegistrationController@store')->name('store');
});

Route::prefix('login')->name('login.')->group(function(){
	Route::get('/', 'AuthenticationController@index')->name('index');
	Route::post('authenticate', 'AuthenticationController@authentication')->name('authenticate');
	Route::get('logout', 'AuthenticationController@logout')->middleware('authenticated.user')->name('logout');
});

Route::middleware('authenticated.user')->group(function(){
	Route::middleware('admin.user')->prefix('admin')->name('admin.')->group(function(){
		Route::resource('users', 'UsersController');
		Route::get('activity', 'UserActivityController@index')->name('activity.index');
	});

	Route::prefix('profile')->name('profile.')->group(function(){
		Route::get('/', 'ProfileController@index')->name('index');
		Route::post('store', 'ProfileController@store')->name('store');
	});

	Route::resource('cart', 'CartController');

	Route::middleware('is_broker')->group(function(){
		Route::resource('listing', 'ListingController');
		Route::get('listing/actions/{id}', 'ListingController@actions')->name('listing.actions');
		Route::post('listing/actions-submit/{id}', 'ListingController@actions_submit')->name('listing.actions_submit');

		Route::get('listing/{id}/image', 'ListingController@image')->name('listing.image');
		Route::post('listing/{id}/image', 'ListingController@image_upload')->name('listing.image_upload');
		Route::get('listing/{listing_id}/image/{id}/remove', 'ListingController@remove')->name('image.remove');
		Route::get('listing/{listing_id}/image/{id}/default/{status}', 'ListingController@default')->name('image.default');
	});
	Route::get('unit-address-search', 'ListingController@search')->name('listing.unit-address-search');
	Route::get('unit-address-select', 'ListingController@select')->name('listing.unit-address-select');

	Route::get('listing-viewed', 'ViewedController@index')->name('listing.viewed');


	Route::resource('inbox', 'InboxController');
	Route::get('user/search', 'InboxController@search')->name('inbox.search');
	Route::get('notification', 'ViewedController@notification')->name('viewed.notification');

	Route::prefix('reports')->name('reports.')->group(function(){
		Route::get('listing', 'ReportsListingController@index')->name('listing');
		Route::get('listing-print', 'ReportsListingController@print')->name('listing-print');
	});

});

app/User.php
<?php

namespace App;

use Cartalyst\Sentinel\Users\EloquentUser;
use App\BrokerRating;

class User extends EloquentUser
{
    //use Notifiable;
    protected $connection = 'mysql';
    protected $table = 'users';
    protected $fillable = [
        'email', 'password', 'permissions', 'last_login', 
        'first_name', 'last_name', 'is_broker', 'mobile_number', 'phone_number', 
        'agency_name', 'agency_address', 'agency_city',
        'created_at', 'updated_at'
    ];
    protected $hidden = [
        'password',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function action()
    {
        return $this->belongsTo('App\ListingAction', 'id', 'client_id');
    }

    public function getRatingAttribute()
    {
        $count = BrokerRating::whereBrokerId($this->id)->count();
        $score = BrokerRating::whereBrokerId($this->id)->sum('rating');

        if ($count > 0) {
            $total_score = $score/$count;
            $star_rating = '';

            for($i = 1; $i <= $total_score; $i++) {
                $star_rating .= '<i class="fa fa-star-color fa-star"></i>';
            }

            for($n = 1; $n <= (5 - $total_score); $n++) {
                $star_rating .= '<i class="fa fa-star-color fa-star-o"></i>';
            }

            if(is_double($total_score)) {
                $star_rating .= '<i class="fa fa-star-color fa-star-half-empty"></i>';
            }

            return $star_rating;
        }
        return 0;
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UsersController extends Controller
{
	public function index(Request $request)
	{
		$search = '';
		$query = new User;
		if ($request->has('search') && $request->search != '') {
			$search = $request->search;
			$query = $query->where('first_name', 'LIKE', "%$search%")->orWhere('last_name', 'LIKE', "%$search%");
		}
		$rows = $query->paginate(50);
		$data = compact('rows', 'search');
		return view('admin.user.index', $data);
	}

	public function show($id)
	{
		$row = User::find($id);
		if(is_null($row)) {
			abort(404);
		}
		$data = compact('row');
		return view('admin.user.show', $data);
	}
}

resources/views/admin/user/index.blade.php
@extends('layout.master')

@section('page-title', 'Users')

@section('content')

<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell large-12">
        <h3>Users Information</h3>
        <form method="get" action="">
            <div class="grid-x">
                <div class="cell large-2">
                    <input type="text" name="search" value="{{ $search }}">
                </div>
                <div class="cell large-1">
                    <button class="button" type="submit">Search</button>
                </div>
                <div class="cell auto">&nbsp;</div>
            </div>
        </form>
        <table width="100%">
            <thead>
                <tr>
                    <th width="8%"></th>
                    <th width="10%" class="text-center">Broker</th>
                    <th width="35%">Name</th>
                    <th width="30%">E-Mail</th>
                    <th width="17%">Registered At</th>
                </tr>
            </thead>
            <tbody>
            @foreach($rows as $row)
                <tr>
                    <td>
                        <a href="{{ route('admin.users.show', $row->id) }}" title="User Information"><i class="fa fa-edit"></i></a>
                        <a href="{{ route('admin.activity.index', ['user_id'=>$row->id]) }}" title="Log Information"><i class="fa fa-cogs"></i></a>
                    </td>
                    <td class="text-center">{{ ($row->is_broker)? 'Yes' : 'No' }}</td>
                    <td>{{ $row->first_name . ' ' . $row->last_name }}</td>
                    <td>{{ $row->email }}</td>
                    <td>{{ $row->created_at->format('M. d, Y H:i A') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $rows->appends(['search'=>''])->links('vendor.pagination.default') !!}
    </div>

</div>

@endsection

@section('scripts')
<script type="text/javascript">
</script>
@endsection

resources/views/admin/user/show.blade.php
@extends('layout.master')

@section('page-title', 'User Information')

@section('content')


<div class="grid-x grid-padding-x margin-top-custom-30">

    <div class="cell auto"></div>

    <div class="cell large-4">
        <div class="callout secondary">
            <h3>Profile</h3>
            @include('partials.error-messages')
            <form action="{{ route('profile.store') }}" method="post">
                <label>
                    Email
                    <input type="email" name="email" id="email" value="{{ $row->email }}" readonly="">
                </label>
                <div class="grid-x grid-padding-x text-center">
                    <fieldset class="large-12 cell">
                        <input type="checkbox" name="is_broker" value="1" id="is_broker" disabled=""><label for="is_broker">I am a professional broker</label>
                    </fieldset>
                </div>
                <h5 class="margin-top-custom-20">Personal Information</h5>
                <label>
                    First Name
                    <input type="text" name="first_name" id="first_name" value="{{ $row->first_name }}" readonly="">
                </label>
                <label>
                    Last Name
                    <input type="text" name="last_name" id="last_name" value="{{ $row->last_name }}" readonly="">
                </label>
                <label>
                    Mobile Number
                    <input type="text" name="mobile_number" id="mobile_number" value="{{ $row->mobile_number }}" readonly="">
                </label>
                <label>
                    Phone Number
                    <input type="text" name="phone_number" id="phone_number" value="{{ $row->phone_number }}" readonly="">
                </label>
                <div class="broker" style="display: none;">
                    <h5 class="margin-top-custom-20">Agency Information</h5>
                    <label>
                        Agency Name
                        <input type="text" name="agency_name" id="agency_name" value="{{ $row->agency_name }}" readonly="">
                    </label>
                    <label>
                        Agency Address
                        <input type="text" name="agency_address" id="agency_address" value="{{ $row->agency_address }}" readonly="">
                    </label>
                    <label>
                        Agency City
                        <input type="text" name="agency_city" id="agency_city" value="{{ $row->agency_city }}" readonly="">
                    </label>
                </div> 
            </form>
        </div>
    </div>

    <div class="cell auto"></div>

</div>
@endsection

@section('scripts')
<script type="text/javascript">
    $(function(){
        <?php
        if ($row->is_broker == 1) {
            echo '$("#is_broker").attr("checked", true);';
            echo '$(".broker").show();';
        }
        ?>
        $('#is_broker').change(function(){
            var is_broker = $(this).is(':checked');
            if (is_broker) {
                $('.broker').show();
            } else {
                $('.broker').hide();
            }
        });
    });
</script>
@endsection